[storage]
# Storage location for portcache
location = "/var/cache/portcache"

[fetcher]
# Gentoo mirrors to use for fetching
# Available mirrors: https://www.gentoo.org/downloads/mirrors/
# Only supports http and https mirrors
mirrors = []

[server]
# address the server should listen on
address = "127.0.0.1"

# port the server should listen on
port = 8000

[repo]
# sync interval in minutes
sync_interval = 5

# list of repo urls
repos = [
    "https://github.com/gentoo-mirror/gentoo",
    "https://github.com/gentoo-mirror/xarblu-overlay"
]
