[storage]
# Storage location of the cache
location = "/var/cache/portcache"

[fetcher]
# Gentoo mirrors to use for fetching
# Available mirrors: https://www.gentoo.org/downloads/mirrors/
# Only supports http and https mirrors
mirrors = [
    "https://ftp.halifax.rwth-aachen.de/gentoo/",
    "http://ftp.halifax.rwth-aachen.de/gentoo/",
]
